apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: development
  labels:
    app: events-internal
  name: events-internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-internal
  strategy: {}
  template:
    metadata:
      labels:
        app: events-internal
    spec:
      containers:
<<<<<<< HEAD
      - image: gcr.io/mar-roidtc309/texopsdocker-demo:v0.1
=======
      - image: gcr.io/mar-roidtc318/texopsdocker-demo:v0.1
>>>>>>> 4e8cbae283d630913abd62682567b6616535e99b
        name: events-internal
        imagePullPolicy: "Always"
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.1"
          limits:
            memory: "256Mi"
            cpu: "0.2"
status: {}
