apiVersion: v1
kind: Service
metadata:
  namespace: development
  labels:
    app: events-internal
  name: events-internal
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    app: events-internal
  type: LoadBalancer
status:
  loadBalancer: {}
